# Site settings
title: Dockito
email: paulo@ragonha.me
description: Docker development box.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dockito.org" # the base hostname & protocol for your site
twitter_username: pirelenito
github_username:  dockito

# Build settings
markdown: kramdown
